

![](https://i.imgur.com/qcnkPh9.png)


![](https://i.imgur.com/zu8hjVF.png)




```js
  

const promise = new Promise((resolve, reject) => {

  const fileLoaded = true;

  

  if (fileLoaded) {

    resolve("File is Loaded");

  } else {

    reject("File is NOT Loaded");

  }

});

  

promise.then((value) => console.log(value));
```

**output:- File is Loaded**


**if false get Error**

![](https://i.imgur.com/ImcoMFd.png)


**so avoid this we will do catch method.**

```js
  

const promise = new Promise((resolve, reject) => {

  const fileLoaded = false;

  

  if (fileLoaded) {

    resolve("File is Loaded");

  } else {

    reject("File is NOT Loaded");

  }

});

  

promise

  .then((value) => console.log(value))

  .catch((error) => console.log(error));
```

**output:- File is NOT Loaded**



# next

```js
  

const promise = new Promise((resolve) => {

  setTimeout(resolve, 3000);

});

  

promise.then(() => console.log("Thanks for waiting!"));
```

**output:- Thanks for waiting!**


# also a way

```js
  

const wait = (time) =>

  new Promise((resolve) => {

    setTimeout(resolve, time);

  });

  

wait(3000).then(() => console.log("Thanks for waiting!"));
```



